In [ ]:
import numpy as np

A = np.arange(6).reshape(3, 2)
B = np.arange(8).reshape(2, 4)

AB_dot = np.dot(A, B)
print(AB_dot)

AB_dot_max = AB_dot.max()
print(AB_dot_max)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
